## Dependencies configuration parameters
redisDependencyEnabled: true
mariadbDependencyEnabled: true
postgresqlDependencyEnabled: false

## MariaDB Configuration
mariadb:
  architecture: standalone
  auth:
    rootPassword: ref:passbolt-db:MARIADB_ROOT_PASSWORD
    username: passbolt
    password: ref:passbolt-db:DATASOURCES_DEFAULT_PASSWORD
    database: passbolt
  primary:
    persistence:
      enabled: false # Disable persistence for testing
      size: 8Gi

## Redis Configuration
redis:
  auth:
    enabled: true
    password: "P4ssR3dis"
  sentinel:
    enabled: false

## Passbolt configuration
app:
  image:
    repository: passbolt/passbolt
    tag: latest-ce
  database:
    kind: mariadb
  tls:
    autogenerate: true
  databaseInitContainer:
    enabled: true
    timeoutSeconds: 600  # Increase timeout to allow more time for database connection

passboltEnv:
  plain:
    APP_FULL_BASE_URL: https://passbolt.local:30433
    PASSBOLT_SSL_FORCE: true
    PASSBOLT_REGISTRATION_PUBLIC: true
    CACHE_CAKE_DEFAULT_SERVER: passbolt-redis-master
  secret:
    DATASOURCES_DEFAULT_USERNAME: passbolt # Database username
    EMAIL_TRANSPORT_DEFAULT_USERNAME: tallgareth@fea.st # SMTP username
    DATASOURCES_DEFAULT_PASSWORD: ref:passbolt-db:DATASOURCES_DEFAULT_PASSWORD
    EMAIL_TRANSPORT_DEFAULT_PASSWORD: ref:fastmail-smtp:EMAIL_TRANSPORT_DEFAULT_PASSWORD
    PASSBOLT_GPG_SERVER_KEY_FINGERPRINT: "your_gpg_fingerprint"
    CACHE_CAKE_DEFAULT_PASSWORD: "P4ssR3dis"

# # Custom NodePort service injected at helm install by inject-nodeport.yaml
service:
  type: NodePort

## Optional Persistence Configuration
persistence:
  enabled: false
